services:
  musashi: 
    build:
      context: .
      dockerfile: ../docker/musashi/Dockerfile
    ports:
      - "8887:8888"
    ipc: host
    stdin_open: true
    tty: true
    volumes:
      - ../:/Musashi-AI
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]