services:
  musashi: 
    build:
      context: .
      dockerfile: ../docker/musashi/Dockerfile
    ports:
      - "8887:8888"
    ipc: host
    stdin_open: true
    tty: true
    volumes:
      - ../:/Musashi-AI
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]

  # yolov5_obb: 
  #   build:
  #     context: .
  #     dockerfile: ../docker/yolov5_obb/Dockerfile
  #   ports:
  #     - "6006:6006" # For Tensorboard
  #   volumes: 
  #     - ./:Musashi-AI
  #   ipc: host
  #   stdin_open: true
  #   tty: true
  #   deploy:
  #     resources:
  #       reservations:
  #         devices:
  #           - capabilities: [gpu]